// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyChanges'](arg1, arg2, arg3);
}

export function CompareFiles(arg1, arg2) {
  return window['go']['main']['App']['CompareFiles'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MergeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeFiles'](arg1, arg2, arg3);
}
