// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyChanges(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CompareFiles(arg1:string,arg2:string):Promise<main.DiffResult>;

export function Greet(arg1:string):Promise<string>;

export function MergeFiles(arg1:string,arg2:string,arg3:string):Promise<void>;
